$mod = SUPER
source = ~/.config/hypr/profile.conf

monitor = , preferred, auto, 1

input {
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    layout = dwindle
}

decoration {
    rounding = 4
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

exec-once = mako
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

bind = $mod, Return, exec, $terminal
bind = $mod, Space, exec, $launcher
bind = $mod, B, exec, $browser
bind = $mod, E, exec, $files
bind = $mod, V, exec, $clipboard
bind = $mod, Q, killactive,
bind = $mod SHIFT, E, exit,
bind = $mod, F, fullscreen, 1

bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d

bindm = $mod, mouse:272, movewindow,
bindm = $mod, mouse:273, resizewindow,
