$mod = SUPER
source = ~/.config/hypr/profile.conf

# Empty monitor name means “apply to all monitors”.
monitor = , preferred, auto, 1

input {
    kb_layout = us
    kb_variant = altgr-intl
    kb_options = lv3:ralt_switch
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    layout = dwindle
}

decoration {
    rounding = 4
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

layerrule = match:namespace noctalia-shell:regionSelector, no_anim on

exec-once = uwsm app -- mako
exec-once = uwsm app -- noctalia-shell
exec-once = uwsm app -- wl-paste --type text --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store

bind = $mod, Return, exec, $terminal
bind = $mod, Space, exec, $launcher
bind = $mod, B, exec, $browser
bind = $mod, E, exec, $files
bind = $mod, V, exec, $clipboard
bind = $mod SHIFT, S, exec, noctalia-shell ipc call plugin:screen-shot-and-record screenshot
bind = $mod, Q, killactive,
bind = $mod SHIFT, E, exit,
bind = $mod, F, fullscreen, 1

bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Volume keys (XF86 special keys) - using exact syntax
bind = , XF86Calculator, exec, gnome-calculator
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86AudioPlay, exec, wpctl set-source @DEFAULT_AUDIO_SOURCE@ toggle
bind = , XF86AudioNext, exec, wpctl set-source @DEFAULT_AUDIO_SOURCE@ next
bind = , XF86AudioPrev, exec, wpctl set-source @DEFAULT_AUDIO_SOURCE@ prev
bind = , XF86AudioStop, exec, wpctl set-source @DEFAULT_AUDIO_SOURCE@ stop
